### ISSUE TITLE
Memindahkan proses validasi request input data menggunakan Form Request

### ISSUE THREAD

**Issue by yohangdev** [setiadijoe/learning-laravel-basic#1]
Saya lihat beberapa validasi masih dilakukan di Controller. Sebaiknya dipindahkan menggunakan **Form Request** 😁 

**File:**
app/Http/Controllers/AuthorController.php
app/Http/Controllers/CategoryController.php
app/Http/Controllers/BookController.php

**Referensi:**
https://laravel.com/docs/8.x/validation#form-request-validation

**Comment by setiadijoe** [comment]
@yohang88 mas, kayak gini kan ya?

**Comment by yohangdev** [comment]
@setiadijoe iyes 💯 👍 jangan lupa itu authorize()-nya juga disesuaikan (true) 😁

**Comment by setiadijoe** [comment]
ini sekalian dengan issue #2
